### PR TITLE
fix : modified styling of Notes Card on main screen

### PR DESCRIPTION
**Pull request by TharunBalaji2004**
Hello @utkarsh006, I cam across you project on Hacktoberfest Discord channel. I downloaded and tested your app, and I'm interested to contribute towards it.

I found that the Notes UI card was not properly visible due to the font color. 

I have modified the Color scheme and styled the Notes UI Card.

Kindly review my PR 😊
#hacktoberfest2023

### CODE REVIEW

**Comment by utkarsh006** [comment]
@TharunBalaji2004 Kindly add working video of your PR and we are good to go :)

**Comment by TharunBalaji2004** [comment]
Yeah sure, These are working clips of Notes UI Card

[Old Notes UI.webm](https://github.com/utkarsh006/Notes-app-compose/assets/95350584/d38e80a4-5ecf-43ff-b0f4-25ce43407880)

[New Notes UI.webm](https://github.com/utkarsh006/Notes-app-compose/assets/95350584/2d2b0c6f-494a-44a6-9d04-5bd8a3fc1f69)

**Comment by utkarsh006** [comment]
@TharunBalaji2004 Raise issue for this PR

**Comment by TharunBalaji2004** [comment]
@utkarsh006 Yeah alright I have raised a issue(#3)

**Pull request merged**
